name: rescue-net-ai
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  
  # Scientific Computing Stack
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Machine Learning Libraries
  - scikit-learn>=1.3.0
  - xgboost>=1.7.0
  - lightgbm>=4.0.0
  - imbalanced-learn>=0.11.0
  
  # Deep Learning Frameworks
  - tensorflow>=2.13.0
  - keras>=2.13.0
  
  # Web Framework and API
  - flask>=2.3.0
  - flask-cors>=4.0.0
  - requests>=2.31.0
  - jsonschema>=4.19.0
  
  # Development and Jupyter
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - notebook>=6.5.0
  - jupyterlab>=4.0.0
  
  # Utilities
  - psutil>=5.9.0
  - python-dotenv>=1.0.0
  - pyyaml>=6.0.0
  - tqdm>=4.65.0
  - joblib>=1.3.0
  
  # Development Tools
  - pytest>=7.4.0
  - pytest-flask>=1.2.0
  - black>=23.7.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  - isort>=5.12.0
  
  # Data Processing
  - openpyxl>=3.1.0
  - xlrd>=2.0.0
  
  # Pip-only packages
  - pip>=23.0.0
  - pip:
    - python-telegram-bot==20.4
    - twilio==8.5.0
    - gunicorn==21.2.0
    - waitress==2.1.2
    - heartpy>=1.2.7
    - biosppy>=2.2.0
